language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 3.5
    - os: osx
      language: generic

branches:
  only:
    master
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - pip3 install --upgrade pip
install:
  - pip3 install --upgrade -r travis-ci-requirements.txt
  - python setup.py develop
before_script:
  - mkdir testrunner
  - cp .coveragerc testrunner/
  - cd testrunner
script:
  - coverage run -m nose.core traits --exe
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
