language: python
sudo: false
matrix:
  include:
  - python: 2.7
    env: REQUIREMENTS=ci-requirements.txt
  - python: 3.4
    env: REQUIREMENTS=ci-requirements.txt
  - python: 3.5
    env: REQUIREMENTS=ci-requirements.txt
  - python: 3.6
    env: REQUIREMENTS=ci-requirements.txt
  - python: 2.7
    env: REQUIREMENTS=ci-requirements-latest.txt
  - python: 3.6
    env: REQUIREMENTS=ci-requirements-latest.txt
  allow_failures:
  - python: 2.7
    env: REQUIREMENTS=ci-requirements-latest.txt
  - python: 3.6
    env: REQUIREMENTS=ci-requirements-latest.txt

branches:
  only:
    master
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - pip install wheel
install:
  - pip install -r "./ci/${REQUIREMENTS}"
  - python setup.py develop
before_script:
  - mkdir testrunner
  - cp .coveragerc testrunner/
  - cd testrunner
script:
  - coverage run -m nose.core traits --exe
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  - pip install coveralls
  - coveralls
