build: false
shallow_clone: true
environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - python: "C:/Python27-x64"
      sdkver: "v7.0"
      REQUIREMENTS: "ci-requirements.txt"

    - python: "C:/Python34-x64"
      sdkver: "v7.1"
      REQUIREMENTS: "ci-requirements.txt"

    - python: "C:/Python35-x64"
      sdkver: "v7.1"
      REQUIREMENTS: "ci-requirements.txt"

    - python: "C:/Python36-x64"
      sdkver: "v7.1"
      REQUIREMENTS: "ci-requirements.txt"

    - python: "C:/Python27-x64"
      sdkver: "v7.0"
      REQUIREMENTS: "ci-requirements-latest.txt"

    - python: "C:/Python34-x64"
      sdkver: "v7.1"
      REQUIREMENTS: "ci-requirements-latest.txt"

    - python: "C:/Python35-x64"
      sdkver: "v7.1"
      REQUIREMENTS: "ci-requirements-latest.txt"

    - python: "C:/Python36-x64"
      sdkver: "v7.1"
      REQUIREMENTS: "ci-requirements-latest.txt"

matrix:
  allow_failures:
  - REQUIREMENTS: "ci-requirements-latest.txt"

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
install:
  - ps: python -m pip install --upgrade --no-binary wheel pip
  - ps: pip install --upgrade wheel
  - ps: pip --version
  - cmd /v:on /e:on /c ".\ci\appveyor-install.cmd"
test_script:
  - ps: md testrun
  - ps: cd testrun
  - ps: coverage run -m nose.core -v traits --exe
